python run_translation.py \
    --config_name ./configs/bart-tiny.json \
    --tokenizer_name ../tokenizers/bpe_combined_ByteLevel_8000vocab_10000subset.json \
    --output_dir ../models/bart-tiny-lr1e-4 \
    --train_file ../data/jsonlines/train.json \
    --validation_file ../data/jsonlines/valid.json \
    --source_lang bytecode \
    --target_lang code \
    --per_device_train_batch_size 128 \
    --learning_rate 1e-4 \
    --warmup_steps 500 \
    --num_train_epochs 100 \
    --generation_max_length 1024 \
    --max_target_length 1024 \
    --evaluation_strategy epoch \
    --do_train \
    --do_eval \
    --max_eval_samples 32 \
    --predict_with_generate \
    --generation_num_beams=4
